baseURL                   = "https://sfdvw.de"
builddrafts                = false
languageCode               = "de-DE"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "sfdvw.github.io"
enableEmoji                = true
hasCJKLanguage             = false
summaryLength              = 150
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Sendung für die vernetzte Welt"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/globe.png"               # from static/
  avatar                   = "img/profile.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Sendung für die vernetzte Welt"
  description              = ["Radio Corax Freies Radio im Raum Halle", "Immer am dritten Samstag des Monats", "20.00 Uhr live"]           # appears in the site header when set to a non-empty string
  images                   = ["img/twitterprofile.png"]
  welcome_head             = "Hello, World!  \\o/"
  welcome_word             = "Technik ~ Gesellschaft ~ Internet ~ neue Medien"

  latestpostscount         = 13                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "SfdvW@radiocorax.de"
  github                   = "https://github.com/sfdvw"
  twitter                  = "https://twitter.com/sfdvwelt"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
